version: '3'
services:
  purm-mysql:
    image: mysql:8.0.25
    container_name: purm-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: MPS
      MYSQL_USER: 'tranlam'
      MYSQL_PASSWORD: 'Calendar20'
      LANG: C.UTF-8
    ports:
      - 6306:3306

